### ISSUE TITLE
Etablissement incorrectement marqué comme fermé

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/search-api#369]
https://recherche-entreprises.api.gouv.fr/search?q=61662009200109
https://annuaire-entreprises.data.gouv.fr/etablissement/61662009200109
https://api-avis-situation-sirene.insee.fr/identification/pdf/61662009200109

Pistes : 
- etablissement fermé puis réouvert en 2008
- ou migration insee en cours qui a pu introduire des bug dans les fichiers stocks.

**Comment by HAEKADI** [comment]
L'état administratif indiqué dans le dernier fichier des établissements est répertorié comme étant "fermé".
Cette situation pourrait être due aux anomalies constatées lors de la dernière mise à jour de Sirene V4, comme mentionné dans l'e-mail de l'INSEE. 

Il serait nécessaire de vérifier cette information lors de la publication des nouveaux fichiers de stocks pour le mois de mai.

**Comment by XavierJp** [comment]
Corrigé avec les derniers stocks on dirait 
https://annuaire-entreprises.data.gouv.fr/etablissement/61662009200109

**Comment by XavierJp** [comment]
résolu
https://recherche-entreprises.api.gouv.fr/search?q=61662009200109
https://annuaire-entreprises.data.gouv.fr/etablissement/61662009200109
