### ISSUE TITLE
[Géolocalisation] Erreur de parsing lorsque le radius est de 0

### ISSUE THREAD

**Issue by MKCG** [annuaire-entreprises-data-gouv-fr/search-api#375]
## Sujet du problème

Actuellement le champs radius accepte 0 pour valeur minimale et aboutit à une requête de geo distance recherchant les établissements dans un rayon de 0 km. Or Elasticsearch (et Lucene), impose une distance minimale strictement supérieure à 0, par exemple 0.001

## Comment le reproduire ?

Par exemple, la recherche suivante aboutit à une erreur d'interprétation de la requête pour cette raison : https://recherche-entreprises.api.gouv.fr/near_point?lat=48.6938081&long=2.1168451&radius=0

Tandis que les recherches suivantes fonctionnent :
- https://recherche-entreprises.api.gouv.fr/near_point?lat=48.6938081&long=2.1168451&radius=1
- https://recherche-entreprises.api.gouv.fr/near_point?lat=48.6938081&long=2.1168451&radius=0.001

## Comportement attendu

Soit : 
- on continue d'autoriser le radius 0 mais on l'interprête comme 0.001km (distance max d'un mètre donc) mais ça rend le comportement de l'API incongru
- on augmente la valeur minimale du champ radius

**Comment by HAEKADI** [comment]
Oui, normalement le radius doit être supérieur à 0 mais avec la refacto de l'API et l'introduction de Pydantic, ce bug est introduit.
