### ISSUE TITLE
[BUG][ADRESSE] Problème d'encoding sur une apostrophe

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/search-api#394]
Dans l'adresse de Stellantis :

https://recherche-entreprises.api.gouv.fr/search?q=542065479

**Comment by HAEKADI** [comment]
Toutes les adresses sont concernées. Il y a un problème d'encodage du côté de data.gouv. L'INSEE utilise des single quotes simples à la place des apostrophes dans les libellés de voie. Ces caractères spéciaux sont mal interprétés par le workflow de géolocalisation de data.gouv.

**Comment by HAEKADI** [comment]
Résolu côté data.gouv. Merci @geoffreyaldebert.
