### ISSUE TITLE
[Qualité des données] Extract pour la DGE

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/search-api#427]
Deux extracts : 
```
Objectif : identifier dans le RNE les sociétés civiles agricoles au RCS
Volume : ~ 1356 sociétés
Filtre :
- Code « APE 01.21Z - Culture de la vigne »
- Catégorie juridique « 6599 - Autre société civile »
- Forme juridique au RCS « Société civile agricole » (on ignore pour notre extract)
Champs de sortie : SIREN, DENOMINATION, REGISTRE, FORME JURIDIQUE RCS
```
Et
```
Objectif : corriger les données au répertoire SIRENE pour les succursales
(3220 - Société étrangère non immatriculée au RCS qui devraient être en 3120 - Société commerciale étrangère immatriculée au RCS)
J’ai une liste fournie par l’INPI pour restreindre la requête (3219 dans le fichier DGFiP + 255 dans le fichier URSSAF).
Filtres : 
- Catégorie juridique « 3220 - Société étrangère non immatriculée au RCS »
- Présence d’au moins un établissement actif en France
Champs de sortie : SIREN, DENOMINATION, NOMBRE D’ETABLISSEMENTS, REGISTRE, FORME JURIDIQUE RCS
```

Les deux extracts peuvent etre fait en deux temps
La colonne REGISTRE va contenir INSEE + RNE + RCS (source IG) 
La colonne FORME JURIDIQUE RCS viendra de IG

**Comment by HAEKADI** [comment]
Je n'ai pas créé la colonne `Registre` en attendant l'extract du RCS. Tu trouveras plutôt deux colonne : _from_rne_ et _from_insee_ .

Premier extract :
* J'ai mis que les siren ouverts. Total : **1355** [extract_sociétes_civiles_agricoles.txt](https://github.com/user-attachments/files/17461348/extract_societes_civiles_agricoles.txt).


Deuxième extract :
* J'ai rajouté un exemple de siret actif en France pour chaque siren. Total : **14545**  [extract_succursales.txt](https://github.com/user-attachments/files/17461354/extract_succursales.txt).

**Comment by XavierJp** [comment]
Les extracts ont été enrichis et envoyés a la commanditaire.
